algorithm: PPO
policy: MlpPolicy
total_timesteps: 3000000
n_envs: 8
checkpoint_freq: 100_000
eval_freq: 20_000
gamma: 0.99
learning_rate: 3e-4
n_steps: 2048
batch_size: 64
gae_lambda: 0.95
ent_coef: 0.0
clip_range: 0.2
vf_coef: 0.5
max_grad_norm: 0.5 