# Phase-2 fine-tuning overrides
# Load best phase-1 checkpoint and use smaller step size
resume_model_path: models/best_model.zip

# Optimiser params (smaller, safer updates)
learning_rate: 3e-5
ent_coef: 0.01

total_timesteps: 800000  # 2 M
n_envs: 8
eval_freq: 20000